package mm.dat.com.queryCreationTool;

import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;

public enum NRCEnum {

	AAA, AHGAPA, AHGAYA, AHLANA, AHMANA, AHMATA, AHMAYA, AHMAZA, AHPHANA, AHSANA, AHTANA, AHYATA, AKB, ALE, ALN, AMA, APPLY, ARGN, AYW, BAAHNA, BAHANA, BAKALA, BALAKA, BALAKHA, BALANA, BAMANA, BAPANA, BATAHTA, BATALA, BATHASA, BATHATA, BGL, BHN, BLN, BRGN, BSMW, BSNW, BTHG, BVN, CATZ, CATZN, CFI, CGN, CHK, CMTSI, CMTSL, CMTST, COI, CRGN, CZN, DADAYA, DAGAMA, DAGANA, DAGASA, DAGATA, DAGAYA, DALANA, DAMASA, DAN, DANAPHA, DAOUNA, DAPANA, DAPAYA, DBM, DBN, DDE, DDY, DGM, DGMIT, DGMMTT, DGMN, DGMNTT, DGMTT, DGN, DGNAC, DGNM, DGNMTE, DGNMTI, DGNMTT, DGSK, DGSKN, DLA, DLN, DNA, DNU, DPN, DRGN, DYSW, EBV, EDENMTT, EDGMMTT, EDGMNTT, EDGNMTT, EDNMTT, EHTYA, ELSO, EMDY, EME, ERSM, ESRM, ETGA, FRGN, GAGANA, GAMANA, GRGN, GRN, GSRN, HAKAKA, HAKHANA, HAMALA, HAPANA, HAPATA, HATHATA, HBI, HBT, HGI, HGO, HGU, HLD, HLE, HLG, HPE, HPW, HRGN, HTAKHANA, HTALANA, HTATALA, HTATAPA, HTAWANA, HTAY, HTAYA, HTYA, HTYE, HUG, HVWA, HYTA, HZA, IDG, IGU, INS, ISAL, ISL, ISM, ISN, ISO, JRGN, KABADA, KABALA, KAHANA, KAHTANA, KAKAHTA, KAKAKA, KAKANA, KAKAYA, KAKHAKA, KAKHANA, KALAAH, KALAHTA, KALANA, KALATA, KALAWA, KAMANA, KAMATA, KAMAYA, KANANA, KAOUTA, KAPAKA, KAPALA, KAPANA, KAPATA, KAPHANA, KASAKA, KASANA, KATAKHA, KATALA, KATANA, KATATA, KATHANA, KAWANA, KAYANA, KCGN, KDO, KGN, KHAAHZA, KHABADA, KHAMAKA, KHAMANA, KHAMASA, KHAOUNA, KHAOUTA, KHAPHANA, KHASANA, KHATANA, KHAYANA, KHU, KIN, KLG, KLN, KLT, KLW, KMA, KMD, KMDE, KME, KMI, KMW, KMYT, KPG, KPU, KRGN, KSE, KTDA, KTHG, KTM, KTN, KTO, KWA, KYGN, KYI, KYN, LABANA, LAHANA, LAKANA, LAKHANA, LAKHATA, LALANA, LAMANA, LAMATA, LAPATA, LATHANA, LATHAYA, LAWANA, LAYANA, LKO, LLM, LMA, LMDW, LNDW, LPA, LPN, LSK, LSO, LTA, LWE, MAAHNA, MAAHPA, MAAHTA, MAAHYA, MAB, MABANA, MADANA, MAG, MAGADA, MAGANA, MAGATA, MAGDN, MAHAMA, MAHTALA, MAHTANA, MAKABA, MAKALA, MAKANA, MAKHABA, MAKHANA, MAKHATA, MALAMA, MALANA, MAMAHTA, MAMAKA, MAMANA, MAMATA, MANAMA, MANANA, MANATA, MANYANA, MAOUNA, MAPANA, MAPATA, MAPHANA, MAPHATA, MASANA, MASATA, MATANA, MATAPA, MATATA, MATAYA, MATHANA, MAWATA, MAYAKA, MAYAMA, MAYANA, MAYATA, MAYNW, MBU, MDG, MDGN, MDGNMTT, MDN, MDY, MDYN, MDYNE, MDYNW, MDYS, MDYSE, MDYSW, MEDN, MGADN, MGD, MGDM, MGDN, MGIW, MGK, MGN, MHA, MHAMY, MHG, MHLG, MHMY, MKA, MKO, MLGN, MMD, MME, MMN, MMO, MMU, MNO, MSU, MTLA, MTNI, MTNT, MUG, MUN, MWA, MYA, MYGN, MYK, NAG, NAHTAKA, NAKANA, NAKHANA, NAKHATA, NAMANA, NAMATA, NAPHANA, NASANA, NATALA, NAYANA, NBN, NDGMMTT, NDGN, NDGNMTT, NDNMTT, NGAPATA, NGAPHANA, NGASANA, NGATHAKHA, NGATHAYA, NGAYAKA, NGAZANA, NKO, NMK, NOFILL, NOK, NOKA, NPW, NRGN, NSG, NTMT, NTN, NTNT, NTU, NWA, NYALAPA, NYAOUNA, NYATANA, NYAYANA, NYGN, NYHE, NZDNMTT, NZGNMTT, OKA, OPO, OTN, OUKAMA, OUKATA, OUTATHA, OWN, PABANA, PABATA, PABATHA, PAG, PAK, PAKAKHA, PAKHAKA, PAKHANA, PAKHATA, PALAAH, PALABA, PALANA, PALAWA, PAMANA, PAN, PANAKA, PANATA, PAOULA, PAPANA, PAPHANA, PASALA, PATAAH, PATANA, PATATA, PATAYA, PATHAKA, PATHANA, PATHAYA, PAWANA, PAYANA, PAZATA, PBDL, PBDN, PDE, PDG, PGDG, PGDGN, PGU, PHAKHANA, PHALANA, PHAMANA, PHAPANA, PHASANA, PHAYASA, PKU, PLW, PMA, PME, PNN, PPDN, PPN, PRE, PRGN, PRS, PTI, PTNW, PTT, PYU, PZDG, PZGG, RGN, SABANA, SAKAKHA, SAKANA, SAKATA, SAKHANA, SALANA, SAMANA, SAPABA, SAPAWA, SAPHANA, SAPTA, SASANA, SATANA, SATAYA, SCG, SDCNMTT, SDG, SDGMMTT, SDGMNTT, SDGMTT, SDGN, SDGNDG, SDGNMTT, SDGNNTT, SDGNTT, SDONMIT, SDONMTT, SDY, SEM, SGDNMTT, SGG, SGN, SIDGNMTT, SKG, SKI, SKM, SKN, SKU, SLOKA, SOAK, SOKA, SOKE, SPAT, SPT, SPTA, SRGN, SRM, SRN, SSG, STBA, STHG, STILL, STPA, TAK, TAKALA, TAKANA, TAKHALA, TAMANA, TANANA, TANGANA, TAPAWA, TASANA, TATAHTA, TATAKA, TATANA, TATANGE, TATAOU, TATATA, TATHANA, TATHAYA, TAV, TAYANA, TAZANA, TBN, TDI, TEMCK, TGA, TGEL, TGEN, TGI, TGKA, TGKM, TGKN, TGO, THAGAKA, THAHTANA, THAKANA, THAKATA, THAKHANA, THALANA, THANANA, THANAPA, THAPAKA, THAPANA, THAPHAYA, THASANA, THATANA, THAWATA, THAYAKHA, THAYANA, TIN, TKA, TKI, TKT, TME, TMN, TPN, TRA, TRGN, TRY, TSN, TTA, TTE, TTN, TTR, TTS, TVY, TYN, TZI, URGN, VRGN, WAKHAMA, WALANA, WAMANA, WATANA, WATHANA, WAW, WAYANA, WKA, WRGN, XRGN, YABANA, YAKANA, YAMANA, YAMAPA, YAMATHA, YANAKA, YANAKHA, YANGANA, YAOUNA, YAPATHA, YAPHANA, YASAKA, YASANA, YATANA, YATAYA, YATHATA, YATHAYA, YBU, YDN, YKM, YKN, YNG, YTN, ZABATA, ZAKANA, ZALANA, ZAYATHA, ZBT, ZLN, ZTA, ZYT;

	private static final List<NRCEnum> VALUES = Collections.unmodifiableList(Arrays.asList(values()));
	private static final int SIZE = VALUES.size();
	private static final Random RANDOM = new Random();

	public static String getNRCCode(int rowNum) {
		// return RANDOM.nextInt(13) + 1 + "/" + getRandomDisrtrict() + "(N)" +
		// getNRCNo(rowNum);
		return 12 + "/" + "DAGANA" + "(N)" + getNRCNo(rowNum);
	}

	private static NRCEnum getRandomDisrtrict() {
		return VALUES.get(RANDOM.nextInt(SIZE));
	}

	private static int createRandomIntBetween(int start, int end) {
		return start + (int) Math.round(Math.random() * (end - start));
	}

	private static String getNRCNo(int rowNum) {
		DecimalFormat decimalFormat = new DecimalFormat("000000");
		return decimalFormat.format(rowNum);
	}
}
